# Config for https://starship.rs/. Requires a https://www.nerdfonts.com/ for that extra ğ“ˆğ’¶ğ“ˆğ“ˆ
# Safety Orange = #FF5F15

format = """
$directory $custom$git_state$git_status
$character
"""

[character]
success_symbol = "[â—](green)"
# success_symbol = "[ï®Š](bold #e3e3e3)[î‚´](black)"
# error_symbol = "[ï®Š ](bold #e3e3e3 bg:#ff6b6b)[î‚´](#ff6b6b)"
error_symbol = "[â—](red)"

[directory]
truncation_length = 8
home_symbol = "ğŸ¡"
format = '[$path]($style)$read_only($read_only_style)'

[directory.substitutions]
'shop-server/areas/platforms/shop-server' = 'shop-server'
'src/areas/' = ''

[git_status]
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
staged = 'ï§ :${count} '
modified = 'ïƒƒ:${count} '
untracked = '??:${count}'
conflicted = "âŒ "
style = "bold #f2f2f2 bg:#FF5F15"
stashed = "$:${count}"
format = '[ $all_status]($style)[î‚´](fg:#FF5F15)'
# format = '[$up_to_date$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind$stashed]($style)[î‚´](fg:#FF5F15)'

[git_branch]
disabled = true
symbol = "ï˜ "
format = "[î‚¶](fg:#FF5F15)[$symbol$branch]($style)"
# style = "bold #ff6bee"
style = "bold #f2f2f2 bg:#FF5F15"
truncation_length = 40

[custom.git_branch_custom]
command = "git symbolic-ref --short HEAD"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
symbol = "ï˜ "
format = "[î‚¶](fg:#FF5F15)[$symbol$output]($style)"
style = "bold #f2f2f2 bg:#FF5F15"

[docker_context]
symbol = "ïŒˆ "

[time]
disabled = true
use_12hr = true
format = " [$time]($style) "

[aws]
symbol = "îŒ½  "
disabled = true

[package]
symbol = "ï£– "

[python]
symbol = "î˜† "
